### PR TITLE
Fixes to latest issues

### LINKED ISSUE #120: [PE-D] Due Date for borrowing a book
I think it might be better to either state in the UG that the due date will be by default 1 month after the starting date or allow the user to actually indicate the due date to make it clearer to the user.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: acyang97/ped#6

### LINKED ISSUE #122: [PE-D] Documentation for displaying tasks on lists
Personally, I think this line is quite vague. I suggest to state “Lists all the tasks including recurring task” instead. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: acyang97/ped#8

### LINKED ISSUE #124: [PE-D] Possible error in Quick Command Reference example
Seems like should been add task tP meeting c/cs2113 for the first one, missing the word task. Similarly for the second one as well.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: acyang97/ped#10

### LINKED ISSUE #125: [PE-D] Possible documentation error/ feature flaw for find method
For the find method, it was stated in the UG that this method searches tasks with a keyword. I think it would be better to specify what your group meant by a keyword. The method works, but if a user happen to type b as the ‘keyword’, the app returns a list of tasks as long as it contains the character ‘b’ in the description. To me or others, keywords for that task might be “board”, “games” and “club”, and typing “find b” should not have returned the following tasks as shown in the picture below. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: acyang97/ped#11

### LINKED ISSUE #132: [PE-D] Confusing Error Handling
The error I'm getting is the format of the date but I follow the format exactly just that I did not include the argument <date/>. So maybe it's better to have another error handling that states exactly what I'm missing.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dixoncwc/ped#4

### LINKED ISSUE #142: [PE-D] UG Bug - Invalid command in UG
Sample example given for add task does not work. Maybe you can update the UG examples in the command summary.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: dojh111/ped#1

### LINKED ISSUE #144: [PE-D] Returned book statuses are not saved
After returning books and exiting the program, upon the next launch, all books are marked as borrowed again. Maybe you can save the statuses of the books when they are altered.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: dojh111/ped#3

### PR DESCRIPTION
**Pull request by MuhammadHoze**
Fixes #120 
Stated in UG that due date will be set to 1 month from loan date.

Fixed #122 
Stated in UG that recurring tasks are also included in `list tasks`.

Fixes #124 
Fixes #142 
Added the word `task` in the quick command reference. 

Fixes #125 
Fixed the `find` command as any letter could be added. Now a **whole word** is only allowed and will be the keyword and not incomplete words.

Fixes #132 
Made changes to the exception message showing the correct format.

Fixes #144 
Fixed the bug upon loading the returned books now shows as [R]; returned instead of previously where even after mark as returned, the book would show as [L] : loaned

### CODE REVIEW

File: src/main/java/seedu/duke/storage/Storage.java [hunk 1]
```diff
@@ -231,6 +231,8 @@ private Book loadBookFromLine(String line) throws DukeException {
             String dateString = arguments[3].trim();
             String futureDateString = arguments[4].trim();
 
+            //System.out.println(isReturn);
+
```
Comment (iamchenjiajun) [inline src/main/java/seedu/duke/storage/Storage.java]: Consider removing this unnecessary comment

**Review by iamchenjiajun — CHANGES_REQUESTED** [review]
Other than the extra comment I think it's good to merge. Also good that some parts of the code are being cleaned up like the JavaDoc.

**Review by iamchenjiajun — APPROVED** [review]

**Comment by iamchenjiajun** [comment]
LGTM!
