### PR TITLE
Bug Fixes

### LINKED ISSUE #161: stringToBoolean incorrect output
If `str` is passed in as anything that is not `0`, it will produce `true`. This might result in bugs from parsing `boolean` types from file in `Storage` class. 

```java
/**
 * Convert strings (either "0" or "1") to booleans (false or true respectively).
 *
 * @param str input string (either "0" or "1")
 * @return false if input string is "0", true otherwise
 */
public static boolean stringToBoolean(String str) {
    if (str.equals("0")) {
        return false;
    }
    return true;
}
```

Possible fix: throw a `DukeException` when `str` is neither `0` nor `1`.

### PR DESCRIPTION
**Pull request by iamchenjiajun**
Fixes #161 

- Allow AY of `9900S1` or `9900S2` to be used.
- Add JUnit tests for new behavior.
- Repackage `Task` test under `model.item`.
- Fix `stringToBoolean`.
- Fix UG errors.

### CODE REVIEW

File: src/main/java/seedu/duke/common/Messages.java [hunk 1]
```diff
@@ -131,6 +131,7 @@
     public static final String EXCEPTION_CATEGORY_NOT_FOUND = "~Error~ Invalid category.";
```
Comment (MuhammadHoze) [inline src/main/java/seedu/duke/common/Messages.java:131]: for line 129, could you help to include ~Error~ at the front like the rest. thanks

**Review by MuhammadHoze — APPROVED** [review]

**Comment by MuhammadHoze** [comment]
LGTM

File: src/main/java/seedu/duke/common/Messages.java (hunk 1 above)
Comment (iamchenjiajun) [reply src/main/java/seedu/duke/common/Messages.java:131]: sure
